//  Product Create Constants

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_ERR = "PRODUCT_CREATE_ERR ";

//  Product Edit Constants

export const PRODUCT_EDIT_REQUEST = "PRODUCT_EDIT_REQUEST";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODUCT_EDIT_ERR = "PRODUCT_EDIT_ERR ";

//  Product Search Constants

export const PRODUCT_SEARCH_REQUEST = "PRODUCT_SEARCH_REQUEST";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
export const PRODUCT_SEARCH_ERR = "PRODUCT_SEARCH_ERR ";


//  Product find Constants

export const PRODUCT_FIND_REQUEST = "PRODUCT_FIND_REQUEST";
export const PRODUCT_FIND_SUCCESS = "PRODUCT_FIND_SUCCESS";
export const PRODUCT_FIND_ERR = "PRODUCT_FIND_ERR ";

//  Product findOne Constants

export const PRODUCT_FINDONE_REQUEST = "PRODUCT_FINDONE_REQUEST";
export const PRODUCT_FINDONE_SUCCESS = "PRODUCT_FINDONE_SUCCESS";
export const PRODUCT_FINDONE_ERR = "PRODUCT_FINDONE_ERR ";

//  CategorY Create Constants

export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_ERR = "CATEGORY_CREATE_ERR ";

//  Category find Constants

export const CATEGORY_FIND_REQUEST = "CATEGORY_FIND_REQUEST";
export const CATEGORY_FIND_SUCCESS = "CATEGORY_FIND_SUCCESS";
export const CATEGORY_FIND_ERR = "CATEGORY_FIND_ERR ";

//  CategorySub create Constants

export const SUBCATEGORY_CREATE_REQUEST = "SUBCATEGORY_CREATE_REQUEST";
export const SUBCATEGORY_CREATE_SUCCESS = "SUBCATEGORY_CREATE_SUCCESS";
export const SUBCATEGORY_CREATE_ERR = "SUBCATEGORY_CREATE_ERR ";



//  wishlist create Constants

export const WISHLIST_CREATE_REQUEST = "WISHLIST_CREATE_REQUEST";
export const WISHLIST_CREATE_SUCCESS = "WISHLIST_CREATE_SUCCESS";
export const WISHLIST_CREATE_ERR = "WISHLIST_CREATE_ERR ";


//  wishlist find Constants

export const WISHLIST_FIND_REQUEST = "WISHLIST_FIND_REQUEST";
export const WISHLIST_FIND_SUCCESS = "WISHLIST_FIND_SUCCESS";
export const WISHLIST_FIND_ERR = "WISHLIST_FIND_ERR ";


//  wishlist delete Constants

export const WISHLIST_DELETE_REQUEST = "WISHLIST_DELETE_REQUEST";
export const WISHLIST_DELETE_SUCCESS = "WISHLIST_DELETE_SUCCESS";
export const WISHLIST_DELETE_ERR = "WISHLIST_DELETE_ERR ";